# Generated by Django 2.2.7 on 2019-11-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthService', '0002_hubapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
