# Generated by Django 2.2.7 on 2019-11-15 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('AuthService', '0003_hub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDevicePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField()),
                ('write_permission', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registred_devices', to='AuthService.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevicePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField()),
                ('write_permission', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_user_perms', to='AuthService.RegisteredDevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_perms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceunit',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceUnit',
        ),
        migrations.AddField(
            model_name='groupdevicepermission',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_group_perms', to='AuthService.RegisteredDevice'),
        ),
        migrations.AddField(
            model_name='groupdevicepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_perms', to='auth.Group'),
        ),
    ]
