# Generated by Django 2.2.7 on 2020-01-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthServiceApp', '0002_auto_20191202_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubapikey',
            old_name='organization',
            new_name='hub',
        ),
    ]
