# Generated by Django 2.2.5 on 2019-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_unit', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('percentage', '%'), ('grams per meter squared', 'g/m**3')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_unit', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.BooleanField()),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_unit', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('celsius', 'C'), ('kelvin', 'K'), ('fahrenheit', 'F')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
