# Generated by Django 2.2.5 on 2019-10-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of_device', models.CharField(choices=[('GTS', 'Generic Temperature Sensor'), ('GHS', 'Generic Humidity Sensor'), ('GL', 'GL')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('input', 'input'), ('output', 'output'), ('inout', 'input/output')], max_length=200)),
                ('type_of_unit', models.CharField(choices=[('humidity', 'Humidity Unit'), ('temperature', 'Temperature Unit'), ('switch', 'Switch Unit')], max_length=200)),
                ('device', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='MQTTApi.Device')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('celsius', 'C'), ('kelvin', 'K'), ('fahrenheit', 'F')], max_length=200)),
                ('device_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MQTTApi.DeviceUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.BooleanField()),
                ('value', models.BooleanField()),
                ('device_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MQTTApi.DeviceUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumidityUnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('percentage', '%'), ('grams per meter squared', 'g/m**3')], max_length=200)),
                ('device_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MQTTApi.DeviceUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
