# Generated by Django 2.2.7 on 2019-11-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MQTTApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of_device', models.CharField(choices=[('GTS', 'Generic Temperature Sensor'), ('GHS', 'Generic Humidity Sensor'), ('GL', 'GL')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('input', 'input'), ('output', 'output'), ('inout', 'input/output')], max_length=200)),
                ('type_of_unit', models.CharField(choices=[('humidity', 'Humidity Unit'), ('temperature', 'Temperature Unit'), ('switch', 'Switch Unit')], max_length=200)),
                ('device', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='MQTTApi.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='humidityunitvalue',
            name='device_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MQTTApi.DeviceUnit'),
        ),
        migrations.AlterField(
            model_name='switchunitvalue',
            name='device_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MQTTApi.DeviceUnit'),
        ),
        migrations.AlterField(
            model_name='temperatureunitvalue',
            name='device_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MQTTApi.DeviceUnit'),
        ),
    ]
