# Generated by Django 2.2.7 on 2019-12-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQTTApi', '0003_connectedunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedunit',
            old_name='to_device',
            new_name='dest_device',
        ),
        migrations.RenameField(
            model_name='connectedunit',
            old_name='to_hub',
            new_name='dest_hub',
        ),
        migrations.RenameField(
            model_name='connectedunit',
            old_name='to_unit',
            new_name='dest_unit',
        ),
    ]
